#
#▀██▀  ▀█▀ ▀██    ▄    ██                       ▄            ▄█▀▀▀▄█                                           ▀██▀▀█▄                    ▄                     ▄                   
# ██    █   ██  ▄██▄  ▄▄▄  ▄▄ ▄▄ ▄▄    ▄▄▄▄   ▄██▄    ▄▄▄▄   ██▄▄  ▀    ▄▄▄▄  ▄▄▄ ▄▄  ▄▄▄▄ ▄▄▄   ▄▄▄▄  ▄▄▄ ▄▄   ██   ██ ▄▄▄ ▄▄    ▄▄▄   ▄██▄    ▄▄▄▄    ▄▄▄▄  ▄██▄    ▄▄▄   ▄▄▄ ▄▄  
# ██    █   ██   ██    ██   ██ ██ ██  ▀▀ ▄██   ██   ▄█▄▄▄██   ▀▀███▄  ▄█▄▄▄██  ██▀ ▀▀  ▀█▄  █  ▄█▄▄▄██  ██▀ ▀▀  ██▄▄▄█▀  ██▀ ▀▀ ▄█  ▀█▄  ██   ▄█▄▄▄██ ▄█   ▀▀  ██   ▄█  ▀█▄  ██▀ ▀▀ 
# ██    █   ██   ██    ██   ██ ██ ██  ▄█▀ ██   ██   ██      ▄     ▀██ ██       ██       ▀█▄█   ██       ██      ██       ██     ██   ██  ██   ██      ██       ██   ██   ██  ██     
#  ▀█▄▄▀   ▄██▄  ▀█▄▀ ▄██▄ ▄██ ██ ██▄ ▀█▄▄▀█▀  ▀█▄▀  ▀█▄▄▄▀ █▀▄▄▄▄█▀   ▀█▄▄▄▀ ▄██▄       ▀█     ▀█▄▄▄▀ ▄██▄    ▄██▄     ▄██▄     ▀█▄▄█▀  ▀█▄▀  ▀█▄▄▄▀  ▀█▄▄▄▀  ▀█▄▀  ▀█▄▄█▀ ▄██▄    
#                                                                                                                                                                                   

# Основные настройки
main-settings:
  # Префикс плагина
  prefix: '&f&l[&c&lЗащита&f&l]'
  # Если указано false, то для ввода пароля нужно будет написать пароль в чат
  use-command: true
  # Команда ввода пароля. (указывается без / в начале) (по умолчанию - pas)
  pas-command: 'pas'
  # Включить ли команды добавления новых игроков в конфиг
  enable-admin-commands: false
  # Отправлять ли анонимную статистику (советую не отключать)
  enable-metrics: true
  # Проверять ли на наличие обновлений (советую не отключать)
  update-checker: true

# Настройки файлов
file-settings:
  # Имя файла с данными игроков. (по умолчанию - data.yml)
  data-file: 'data.yml'
  # Имя файла с логами. (по умолчанию - log.yml)
  log-file: 'log.yml'
  # Если эта настройка включена, то вам нужно будет указать полный путь до файла
  # Пример: root/server/plugins/UltimateServerProtector/data.yml
  use-full-path: false
  # Путь к файлу data.yml
  data-file-path: '/root/server/plugins/UltimateServerProtector/'
  # Путь к файлу log.yml
  log-file-path: '/root/server/plugins/UltimateServerProtector/'
  
# Настройки дополнительных блокировок
blocking-settings:
  # Блокировать ли выбрасывание предметов
  block-item-drop: true
  # Блокировать ли подбор предметов
  block-item-pickup: true
  # Блокировать ли таб-комплит (работает против /ver + tab)
  block-tab-complete: true
  # Делать ли игрока бессмертным во время ввода пароля
  block-damage: true
  # Блокировать ли возможность наносить вред мобам и игрокам во время ввода пароля
  block-damaging-entity: true
  # Блокировать ли триггер мобов на игрока во время ввода пароля
  block-mobs-targeting: true

# Настройки сессии
session-settings:
  # Сохранять ли данные об игроке чтобы ему не нужно было вводить админ пас при перезаходе
  session: true
  # Удалять ли данные об игроке через некоторое время
  session-time-enabled: false
  # Время через которое данные о зарегистрированном игроке удалятся в секундах (отсчет идет от момента ввода пароля)
  session-time: 21600 #(6 часов)

# Настройки наказаний
punish-settings:
  # Включить ли наказания за неверно введенный админ-пароль 
  enable-attempts: true
  # Максимальное число попыток ввода админ-пароля
  max-attempts: 3
  # Включить ли время на ввод админ-пароля
  enable-time: true
  # Время за которое игрок будет должен ввести админ-пароль в секундах
  time: 60

# Настройка боссбара (работает только, если включено время для входа)
bossbar-settings:
  # Включить ли боссбар
  enable-bossbar: true
  # Цвет боссбара (PINK, BLUE, RED, GREEN, YELLOW, PURPLE, WHITE)
  bar-color: RED
  # Тип боссбара (PROGRESS, SEGMENTED_6, SEGMENTED_10, SEGMENTED_12, SEGMENTED_20)
  bar-style: SEGMENTED_12
  
# Настройки повышенной безопасности
secure-settings:
  # Применять ли наказания к операторам которых нет в списке
  enable-op-whitelist: true
  # Применять ли наказания к тем, кто не находится в конфиге, но имеет админ-права
  enable-notadmin-punish: false
  # Применять ли наказания к людям, которые имеют запрещенные права
  enable-permission-blacklist: false
  # Включить ли IPWhitelist для администраторов
  enable-ip-whitelist: false
  # Включить ли возможность использовать команду /usp только из консоли
  only-console-usp: false
  # Выключать ли сервер, если отключается плагин (отключено по умолчанию)
  shutdown-on-disable: false
  # Разрешить ли ряду игроков входить в игру без админ пароля (откллючено по умолчанию и небезопасно!)
  enable-excluded-players: false

# Настройки показа сообщений
message-settings:
  # Задержка между авто-сообщениями и тайтлами в секундах
  delay: 1
  # Включить ли сообщения на весь экран
  send-titles: true
  # Включить ли оповещения для администраторов
  enable-broadcasts: true
  # Включить ли оповещения для консоли
  enable-console-broadcasts: true

# Настройки звуков, которые будут проигрываться при вводе команд/действиях 
sound-settings:
  # Включить ли звуки при командах
  enable-sounds: true
  # Список всех звуков: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
  # Звук при поимке админа с правами
  on-capture: ENTITY_ITEM_BREAK
  # Звук при неверном пароле
  on-pas-fail: ENTITY_VILLAGER_NO
  # Звук при верном пароле
  on-pas-correct: ENTITY_PLAYER_LEVELUP
  # Громкость звука от 0.0 до 1.0
  volume: 0.75
  # Тон звука от 0.5 до 2.0 (больше = "писклявее")
  pitch: 1.0

# Настройка эффектов, которые даются до ввода пароля
effect-settings:
  # Включить ли эффект, который будет выдаваться админу, до ввода пароля
  enable-effects: true
  # Какие эффекты накладывать на игрока (ЭФФЕКТ:УРОВЕНЬ)
  effects:
    - 'BLINDNESS:3'   

# Настройки логгирования
logging-settings: 
  # Записывать ли удачные/неудачные попытки ввода пароля в отдельный файлик
  logging-pas: true
  # Записывать ли присоединения игроков с админ-правами в отдельный файлик
  logging-join: true
  # Записывать ли в файл включение и отключение плагина
  logging-enable-disable: true
  
# Команды, которые будут применяться к нарушителям
commands:

# Команды, которые будут применяться к тем, у кого есть админ-права, но кого нет в конфиге
  not-in-config:
  - 'kick %player% Вас нет в списке администраторов!'
  - 'deop %player%'
  
# Команды, которые будут применяться к тем, у кого есть админ-права, но он не прописан в вайтлисте
  not-in-opwhitelist:
  - 'deop %player%'
  #- 'ban %player% Вам нельзя иметь права оператора!'
  
# Команды, которые будут применяться к тем, кто имеет запрещенные права (отключено по умолчанию)
  have-blacklisted-perm:
  - 'lp user %player% permission clear'
  #- 'ban %player% Вам нельзя иметь такие права!'
  
# Команды, которые будут применяться к тем, кто вошел с админ-правами, указан в конфиге, но имеет не админский IP (отключено по умолчанию)
  not-admin-ip:
  - 'kick %player% Ваш IP не находится в вайтлисте'
  #- 'deop %player'
  
# Команды, которые будут применяться к тем, кто ввел пас неверно за отведенные ему попытки
  failed-pass:
  - 'ban %player% Вы ввели админ-пароль неверно, ваш аккаунт заморожен'
  - 'deop %player%'
  
# Команды, которые будут применяться к тем, кто не ввел пас за отведенное время
  failed-time:
  - 'ban %player% Вы не успели ввести админ-проль за отведенный срок'
  - 'deop %player%'
  
# Права, за которые игроку будет необходимо ввести админ-пароль (не стесняйтесь добавлять свои!)
permissions: 
 - '*'
 - 'bukkit.*'
 - 'minecraft.*'
 - 'essentials.*'
 - 'cmi.*'
 - 'worldguard.*'
 - 'worldedit.*'
 - 'fawe.*'
 - 'permissions.*'
 - 'luckperms.*'
 - 'luckperms.editor'
 - 'luckperms.applyedits'
 - 'citizens.*'
 - 'citizenscmd.*'
 - 'znpcs.*'
 - 'holograms.*'
 - 'multiverse.*'
 - 'coreprotect.*'
 - 'mycommand.*'
 - 'dh.admin'
 - 'ls.admin'
 - 'authme.admin'
 - 'protocol.admin'
 - 'placeholderapi.admin'
 - 'plugman.admin'

# Команды, которые можно вводить до ввода админ-пароля (указывать вместе с /)
allowed-commands:
 - '/l'
 - '/login'
 - '/reg'
 - '/register'
 - '/captcha'

# Каким игрока разрешно иметь ОП права
op-whitelist: 
 - Overwrite
 - test99999
 
# С каких IP разрешено входить игрокам с админ-правами
# Вы можете указать только часть IP адреса, чтобы разрешить вход людям с динамическим IP. К примеру 1.2.3.4 - 1.2.3.
ip-whitelist:
 - 127.0.0.1
 - 0.0.0.0
 # - 1.2.3

# Права, которые никто, кроме игроков из раздела excluded-players, не сможет иметь (отключено по умолчанию. не выставляйте более 100)
blacklisted-perms: 
 - '*'
 
# Какие игроки смогут входить в игру без ввода админ-пароля (не работают некоторые другие проверки)
excluded-players:
 - test99999
 - test123123
